name: 'lotto-actions'
description: 'GitHub Actions for lotto purchase'
author: 'bang9<gusrn1423@naver.com>'
inputs:
  id:
    required: true
    description: 'Input dhlottery id'
    default: ''
  pwd:
    required: true
    description: 'Input dhlottery password'
    default: ''
  token:
    required: true
    description: 'Input github token'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
