name: 'lotto-actions'
description: 'GitHub Actions for lotto purchase'
author: 'bang9<gusrn1423@naver.com>'
inputs:
  lotto_id:
    required: true
    description: 'Input dhlottery id'
    default: ''
  lotto_pwd:
    required: true
    description: 'Input dhlottery password'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
