name: Run actions (manual)
on: workflow_dispatch
jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: node ./dist/index.js
